using System.ComponentModel.DataAnnotations;

namespace InventoryManagement.Entities;

/// <summary>
/// Base class for all entities in the system.
/// Contains common properties that every table should have.
/// </summary>
public abstract class BaseEntity
{
    /// <summary>
    /// Primary Key - Auto-generated by the database
    /// </summary>
    [Key]
    public int Id { get; set; }

    /// <summary>
    /// Soft deactivation flag.
    /// true = active/visible, false = deactivated (hidden but still exists)
    /// </summary>
    public bool IsActive { get; set; } = true;

}